### ISSUE TITLE
Touch events don't work

### ISSUE THREAD

**Issue by joeypoon** [BTMorton/angular2-grid#190]
App works fine on Chrome, Safari, Firefox, and IE11 but loading a page utilizing the grids on an iPad or iPhone renders all touch events null including links not related to the grid. This is true for Safari, Chrome, and Firefox on the iOS devices. Pages without the grid operate as normal.

**Comment by joeypoon** [comment]
Removing '(document:mousemove)': '_onMouseMove($event)' from NgGrid does the trick for me. I'm unsure what this line is intended to do but I don't seem to have lost any functionality from removing this line.

**Comment by BTMorton** [comment]
The main reason for `(document:mousemove)` as well as `(mousemove)` is so that when dragging an item outside of the grid boundaries, if the mouse leaves the item, it doesn't stop the item being dragged. It's a limited use case, I'll admit, but I'd rather figure out what exactly is causing the issue.

**Comment by BTMorton** [comment]
I've made a slight change to the demo site at https://bmorton.co.uk/angular/. Can you give that a try and see if it helps?

**Comment by joeypoon** [comment]
Demo works on ipad.
