### ISSUE TITLE
EXCEPTION: Attempt to use a dehydrated detector

### ISSUE THREAD

**Issue by LPalmito** [BTMorton/angular2-grid#60]
Hey!

I'm currently using angular2-grid and when I move some of my items, I sometime have the error `angular2.dev.js:23597 EXCEPTION: Attempt to use a dehydrated detector: DeviceDetails_2 -> itemChange` coming.

This is the html part of my code concerning the display of the items:
```
<div class="row gray-bg" [ngGrid]="gridConfig">
    <div *ngFor='#widget of widgets; #i = index' [ngGridItem]="getGridInfo(widget)"
         (dragStop)="updateWidgets(i, $event)">
                <graph-widget [currentWidget]="widget"></graph-widget>
                <text-widget [currentWidget]="widget"></text-widget>
        </div>
    </div>
</div>
```

As you can see, I'm using `dragStop` to propagate the event and launch the following method: 
```
    updateWidgets(i: number, pos: { col: number, row: number, sizex: number, sizey: number }) {
        var gridData = {col: pos.col, row: pos.row, sizex: pos.sizex, sizey: pos.sizey};
        var widgets = _.cloneDeep(this.widgets);
        if (this.isBreakpoint('sm') || this.isBreakpoint('xs')) {widgets[i].reducedWidget.gridInfo.sm = gridData}
        else if (this.isBreakpoint('md')) {widgets[i].reducedWidget.gridInfo.md = gridData}
        else if (this.isBreakpoint('lg')) {widgets[i].reducedWidget.gridInfo.lg = gridData}
        this.updated.emit(widgets);
    }
```
but the error mentions `itemChange`, why is that? The issue is certainly coming from the `this.updated.emit(widgets);` because when I comment that line of code, I don't have any issue anymore. But, I need it to send my new `widgets` (which contains the position of each widget. to my store (I'm using redux).

Do you know what is a `dehydrated detector` exactly? And I can I deal with this issue? Any help would be really appreciated, thank you in advance!

**Comment by BTMorton** [comment]
Hmmm, dehydrated detector means that the component that was trying to be used is no longer 'alive', so to speak. Are you completely replacing all of your widgets during this event?

**Comment by LPalmito** [comment]
I'm kind of replacing all my widgets during this event yes, I'm using twice the `cloneDeep` method from `loadash` (mentioned in the following samples of code).

I'm using redux so, following the flux, during this event:
- The `updateWidgets` method is triggered:
```
updateWidgets(i: number, pos: { col: number, row: number, sizex: number, sizey: number }) {
        var gridData = {col: pos.col, row: pos.row, sizex: pos.sizex, sizey: pos.sizey};
        var widgets = _.cloneDeep(this.widgets); // HERE IS A DEEP CLONE
        if (this.isBreakpoint('sm') || this.isBreakpoint('xs')) {widgets[i].reducedWidget.gridInfo.sm = gridData}
        else if (this.isBreakpoint('md')) {widgets[i].reducedWidget.gridInfo.md = gridData}
        else if (this.isBreakpoint('lg')) {widgets[i].reducedWidget.gridInfo.lg = gridData}
        this.updated.emit(widgets);
    }
```
- The `output` emitted by my `updated` `EventEmitter` is caught by my `main` component, which calls the reducer:
```
updateWidgets(widgets: Widget[]) {this.store.dispatch({type: UPDATE_WIDGETS, payload: widgets});}
```
- The reducer replaces the `widgets` in the global store:
```
export const widgets = (state: Array<Widget> = [], {type, payload}) => {
    switch (type) {
        case UPDATE_WIDGETS:
            return _.cloneDeep(payload);  // HERE IS A DEEP CLONE
        default:
            return state;
    }
};
```
- And then the flow of data goes back to my component to update the display.

I need to recreate all the widgets because immutable elements themselves at in the core of redux pattern (http://onehungrymind.com/build-better-angular-2-application-redux-ngrx/). Is there a way to keep redux-friendly and don't have that `dehydrated detector` error anymore?

**Comment by BTMorton** [comment]
All I can think is that something is triggering the itemChange event on one of the items after they have been removed. Is it necessary for you to rebuild _all_ of the items every time? Can you not just update the one that has changed? I'm afraid I can't really help any more as I don't know enough about how Angular 2 works fundamentally. It should have finished the itemChange event before emitting the dragStop event anyway. It might be something to do with removing all of the items together and getting confused because as each item gets removed it does a cascade and then an update of all the other items.

**Comment by Luchillo** [comment]
I'm having the same with just instantiating the grid, maybe it is because the code comes from an async operation from a socket, here's my code:
```ts
export class DashBoard {
  // Angular2-grid
  widgets: any[] = []
  options: any = { 
    max_cols: 12, 
    auto_resize: true, 
    visible_cols: 12,
    col_width: 200,
    col_height: 200 
  }
  constructor(
    public conf: Config,
    public cookieService: CookieService
  ) {
    this.conf.dashboardSocket.subscribe('dashboardObtained', (data: any) => {
      if (data === undefined) {
        return
      }
      console.log('Data: ', data)
      this.widgets = Util.JSONParse(data).widgets
    })
}
```
```html
  <div class="grid" #grid [ngGrid]="options">
    <div class="grid-item" *ngFor="#widget of widgets"
      [ngGridItem]="{col: widget.x, row: widget.y, sizex: widget.width, sizey: widget.height}">
        <!-- <div *ngIf="widget.data_type.includes('value')"> -->
          <div>
            {{ widget.title }}: {{ widget.data[0].value }}
          </div>
        <!-- </div> -->
    </div>
  </div>
```

**Comment by LPalmito** [comment]
>  "Is it necessary for you to rebuild all of the items every time? Can you not just update the one that has changed?"
Unfortunately yes, I need to recreate all the widgets because I'm using redux, and immutable elements themselves at in the core of redux the pattern (http://onehungrymind.com/build-better-angular-2-application-redux-ngrx/). The most important thing in redux is to have every time a global state describing the current state of the application. That's why I would like to be able to update my widgets' position just after moving them.
By the way (the following could be useful not only for redux-pattern app), if I drag a widget A to a widget B previous position, then both A and B will have moved when `dragStop` is triggered. But the `event` in `dragStop` refers only to the widget A isn't it? How could I retrieve the widget B position to update my global state?

Thank you for your help!

**Comment by BTMorton** [comment]
The dragStart/dragStop events are triggered from both NgGrid and the NgGridItems. I suggest that you listen on the items, rather than the grid. There's also the itemChange event on the items which will trigger an update any time any of the item's properties change (col/rol/size/top/left/width/height).

I still don't get why you can't only update the single element that has changed. The rest of the elements remain unchanged so surely that doesn't conflict with the whole immutable feature? Anyway, I've never encountered this issue before. If one of you guys can provide a working example demonstrating it, I'd be more than happy to investigate further.

**Comment by Luchillo** [comment]
Ok i had the same error in the logs, the issue is that i have an async function to get the data for the widgets from an api server, to stop this from happening i put the grid tag hidden with `*ngIf` so that it doesn't try to initialize the component until i have retrieved the data from server:
```ts
export class DashBoard {
  gridVisible: boolean = false
  constructor(){
    this.fromApi((data: any) => {
      if (data === undefined) {
        return
      }
      console.log('Data: ', data)
      this.widgets = Util.JSONParse(data).widgets
      setTimeout(() => {
        this.gridVisible = true
      }, 100)
    })
  }
```
```html
  <div class="grid" [ngGrid]="options" *ngIf='gridVisible'>
    <div class="grid-item" *ngFor="#widget of widgets"
      [ngGridItem]="{col: widget.x, row: widget.y, sizex: widget.width, sizey: widget.height}">
        <div>
          {{ widget.title }}: {{ widget.data[0].value }}
        </div>
    </div>
  </div>
```

**Comment by LPalmito** [comment]
All right, here http://plnkr.co/edit/iP3pUiXhqBm3vmwAI1oN?p=preview is a plunkr where you can find one issue I'm dealing with. How it works: I'm calling `updateWidget(widget)` each time `dragStop` is triggered on a particular `widget`. The idea of `updateWidget` is to update the global `widgets` object. To reproduce the bug:

- drag one widget (let's call it A) to the top of the window,the other widget (let's call it B) will be below
- when finishing dragging, A moves automatically below B, which we don't want

Thanks for taking a look at it! :)

**Comment by Luchillo** [comment]
@LPalmito Some observations, it seems to make the change just with a simple click, the fact is that your `updateWidget()` function is making the swap of both items when i make a simple click and they are stacked one on top of the other, the issue here is that the function is being called just for the item you selected and not for the other items in grid.

**Comment by BTMorton** [comment]
Ok, I know what this is. It turns out the change I made recently (I think?) that removes/adds items when their config updates was terrible (my bad). If you see this plunkr here http://plnkr.co/edit/1MIsMr3ckkvFR3Dgoypr?p=preview I have adjusted it so that it has a new update function. Give the NgGrid.js from that a go with your actual setup and see if it helps. I'll work on getting those changes into master ASAP.

@Luchillo at the same time, I added a new event that triggers on dragStop and resizeStop that emits _all_ items in the grid, or at least the position properties (see plunkr). I'm more than happy to add this to the main grid, however, the issue with this is that the items themselves have no concept of what they're attached to, so should the indexes end up being different the values would be effectively useless. As I've said before, the best way to do this is to use a component wrapper. I'll try to throw together a component and see about including it in a future release, but no promises on it being any time soon, I'm afraid.

**Comment by LPalmito** [comment]
Thanks a lot @BTMorton, everything is working perfectly for me now! By the way, I've changed the way you implemented `updateWidgets`, just to avoid the for loop and replacing it with a map:

- the "for loop" version:
```
  updateWidgets(items: [{ col: number, row: number, sizex: number, sizey: number }]) {
    var widgets = [];
    for (var x in items) {
      var pos = items[x];
      var gridData = {col: pos.col, row: pos.row, sizex: pos.sizex, sizey: pos.sizey};
      var updatedWidget = this.widgets[x];
      if (this.isBreakpoint('sm') || this.isBreakpoint('xs')) {updatedWidget.reducedWidget.gridInfo.sm = gridData}
      else if (this.isBreakpoint('md')) {updatedWidget.reducedWidget.gridInfo.md = gridData}
      else if (this.isBreakpoint('lg')) {updatedWidget.reducedWidget.gridInfo.lg = gridData}
      widgets.push(updatedWidget);
    }
    this.widgets = widgets;
    console.log(widgets);
  }
```
- the "map" version:
```
    updateWidgets(items: [{ col: number, row: number, sizex: number, sizey: number }]) {
        let widgets = items.map((item, i) => {
            let gridData = {col: item.col, row: item.row, sizex: item.sizex, sizey: item.sizey};
            let updatedWidget = this.widgets[i];
            if (this.isBreakpoint('sm') || this.isBreakpoint('xs')) {updatedWidget.reducedWidget.gridInfo.sm = gridData}
            else if (this.isBreakpoint('md')) {updatedWidget.reducedWidget.gridInfo.md = gridData}
            else if (this.isBreakpoint('lg')) {updatedWidget.reducedWidget.gridInfo.lg = gridData}
            return updatedWidget;
        });
        console.log(widgets);
    }
```

@Luchillo Thanks for your help too! One question: instead of using a `setTimeout` in your code, why don't you use `ngAfterViewInit` or `ngAfterContentInit`?

Thanks again to you both! :)

**Comment by BTMorton** [comment]
@LPalmito don't forget to do `this.widgets = widgets` at the end of the function! Yeah, the map is better. What can I say, I was tired when I wrote it :P

**Comment by LPalmito** [comment]
Actually I've made a wrong copy and paste you're right, I've updated my comment in case someone is using the code I've written. In my real project I'm sending `widgets` to a reducer, which is in charge to update the `this.widgets` object. What can I say, I was tired when I copied and pasted it :P hahaha!

More seriously, I've an other issue I wanted to show you (the one I was talking about at the beginning actually!): http://plnkr.co/edit/yDSSAhvOC7zFvhF5IT5M?p=preview. Try that to reproduce it:
- drag widget 1 below widget 2
- use the reload button

The positions are reloaded appropriately, but the `EXCEPTION: Attempt to use a dehydrated detector` appears in the console logs. Do you see a way how I could reload the original positions without having this error?

**Comment by Luchillo** [comment]
@LPalmito The timeout is for giving time to the data to be applied to the variable, if it were put in a `ngAfterContentInit` what ensures the data doesn't take 5 secs to get back from server when massive amounts of data have to be processed? thus using a timeout in the callback of the server post.

**Comment by BTMorton** [comment]
@LPalmito Right, I don't really know what is causing that. The events don't seem to be being triggered after the directive is destroyed which is what I thought was the cause. Maybe one of the angular team can shed some light on the issue? I think it's because you're completely replacing the items but I don't know why it's causing errors, I'm afraid.

**Comment by BTMorton** [comment]
OK, scratch that. It looks like it's because the event emitter is async and removing all the items at once causes a headache. The solution is just to use synchronous events for itemChange. It's not ideal, I guess but it'll fix it!
