### ISSUE TITLE
[Feat] Responsiveness based on percentage?

### ISSUE THREAD

**Issue by Luchillo** [BTMorton/angular2-grid#65]
I've seen some related plugins make their layout responsive by using percentages of the current container to define the size of rows as well as columns.

I think would be very useful that we could define the size of the rows and cols based by percentage, that way will be easier to keep aspect ratio of items, independent of screen size/resolution.

Some plugins use absolutes values, other uses flexbox, idk which fits the most but maybe this gives a few ideas to improve, what do you think?

**Comment by BTMorton** [comment]
What did you have in mind when you say percentage columns? If you set the max number of columns it will size each column equally based on the widget of the grids container? If you mean to pass an array of column widths as percentages, that's probably do-able but would take a fair bit of effort in the resizing areas to make sure the sizes are all correct.

Currently for rows if you do any of the auto sizing it is based upon window height, rather than container height. Mostly because I had a dynamic container height.

Flexbox is an option, I guess. Would be more difficult for the dragging/resizing of boxes as they follow the mouse and having flex in place could easily screw about with that

**Comment by Luchillo** [comment]
The idea is to be able to keep aspect ratio, say i want the grid to have 12 columns at all times, at start it will try to keep same size for row and column, but on resize current code only changes column size, not row size so if resized it looks funny.

**Comment by BTMorton** [comment]
OK, so if I added a new flag `maintainRatio` that updates the size based on the config of row height and column width values, would that do the trick, d'you think? I'll get on it

**Comment by Luchillo** [comment]
You got the point, that's exactly what maintain aspect ratio would be expected to do :smile:
